### ISSUE TITLE
Example call?

### ISSUE THREAD

**Issue by dv336699** [jsreportonline/wkhtmltopdf#1]
Sup @pofider would you mind providing what you're using to send the data to the server including header/footer/cover?

Thanks

**Comment by pofider** [comment]
I'm not sure I understand the question. You mean how the API request to jsreportonline should look like to include the wkhtmltopdf header/ footer?

Would this help? You can send other options if you click `API` button in the settings menu.

**Comment by pofider** [comment]
Forgot the link
https://jsreport.net/learn/wkhtmltopdf#api

**Comment by dv336699** [comment]
Ah, gotcha, thanks for that.
